language: python
python:
  - "2.6"
  - "2.7"
  - "2.8"
  - "3.3"
  - "3.4"
services: 
  - mongodb
install: # command to install dependencies
  - "pip install -r requirements.txt"
# command to run tests
script: python test.py

notifications:
  email:
    - davidawad64@gmail.com

sudo: false
