language: python
python:
  - 2.7
services:
  - mongodb
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python tests/unittest.py

notifications:
  email:
    - contact@davidawad.com

after_success: coveralls --verbose
