##
# @Author David Awad
#

version: '2'

services:

 web:
  build: ./app
  image: spaceshare
  ports:
   - "4000:4000"
  links:
   - mongo:mongo
   - redis:redis
   - celery:celery
  volumes:
   - /usr/src/app/static
   - ".:/app"
  env_file: .env
  command: gunicorn -w 2 -b :8000 server

 nginx:
  restart: always
  build: ./nginx/
  ports:
   - "80:80"
  volumes:
   - /www/static
  links:
   - web:web

 redis:
  image: redis:latest
  command: redis-server
  volumes:
    - './data/redis:/var/lib/redis/data'
  ports:
    - '6379:6379'

 celery:
  build: ./app
  command: celery worker --app=models --loglevel=debug
  depends_on:
    - redis
  volumes:
    - .:/data
  links:
    - redis:6379
  environment:
    - C_FORCE_ROOT=true

 mongo:
  image: mongo:latest
  volumes:
   - "./data/mongo:/data/db"
  ports:
   - "27017:27017"
