

NAME: SpaceShare

DEBUG: True

MANDRILL_USERNAME:
MANDRILL_KEY:


UPLOAD_FOLDER : 'uploads/'

# Celery configuration
CELERY_BROKER_URL : 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND: 'redis://localhost:6379/0'
